[package]
name = "rustdsplit"
version = "1.0.0"
authors = ["epi <epibar052@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
env_logger = "0.7.1"
colored = "1.9"
regex = "1"

[profile.release]
opt-level = 'z'  # optimize for size
lto = true
codegen-units = 1
panic = 'abort'
